sudo: required
servies: 
  - docker

before_install:
  - docker build -t phirani/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true phirani/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-547589912222"
  bucket_path: "docker-react"
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master